"""add period to work experience

Revision ID: e2cefcdbde0d
Revises: tz_compliance_001
Create Date: 2026-04-16 19:47:47.471636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2cefcdbde0d'
down_revision: Union[str, None] = 'tz_compliance_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_receiver', table_name='messages')
    op.drop_index('ix_messages_sender', table_name='messages')
    op.drop_constraint('messages_sender_id_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_receiver_id_fkey', 'messages', type_='foreignkey')
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('work_experiences', sa.Column('period', sa.String(length=100), nullable=True))
    op.alter_column('work_experiences', 'is_current',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_experiences', 'is_current',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('work_experiences', 'period')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key('messages_receiver_id_fkey', 'messages', 'users', ['receiver_id'], ['id'])
    op.create_foreign_key('messages_sender_id_fkey', 'messages', 'users', ['sender_id'], ['id'])
    op.create_index('ix_messages_sender', 'messages', ['sender_id'], unique=False)
    op.create_index('ix_messages_receiver', 'messages', ['receiver_id'], unique=False)
    # ### end Alembic commands ###
