"""Add ai_resume_draft

Revision ID: e31b4e148ea6
Revises: 0003
Create Date: 2026-04-16 07:19:47.668432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""Add ai_resume_draft

Revision ID: e31b4e148ea6
Revises: 0003
Create Date: 2026-04-16 07:19:47.668432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e31b4e148ea6'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('ai_resume_draft', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'ai_resume_draft')
    # ### end Alembic commands ###
